repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
-   repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-install
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: poetry run pytest -n auto --random-order
        language: system
        pass_filenames: false
        types_or:
        -   html
        -   python
    -   id: coverage-check
        name: coverage-check
        entry: ./checkcoverage.sh
        language: system
        pass_filenames: false
        types_or:
        -   html
        -   python
