site_name: Convoke


repo_url: https://github.com/eykd/convoke
repo_name: eykd/convoke


theme:
  name: material
  palette:
    scheme: slate


plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            docstring_style: sphinx
